steps:
  - name: 'python:3.10-slim'
    id: Install dependencies
    entrypoint: 'python'
    args: ["-m", "pip", "install", "-r", "./chapter03/requirements.txt" ,"--user"]

  - name: 'python:3.10-slim'
    id: Lint
    entrypoint: 'python'
    args: ["-m", "pylint", "./chapter03/scripts/create_test_dataset.py"]


  - name: 'python:3.10-slim'
    id: Black formatter
    entrypoint: 'python'
    args: ["-m", "black", "./chapter03/scripts/create_test_dataset.py"]


  - name: 'python:3.10-slim'
    id: Create BigQuery dataset
    entrypoint: 'python'
    args: ["./chapter03/scripts/create_test_dataset.py", "-l", "${LOCATION}", "-n", "test_dataset"]
    env:
      - "LOCATION=$LOCATION"
