steps:
  - name: 'python:3.10-slim'
    id: Install dependencies
    entrypoint: 'python'
    args: ["-m", "pip", "install", "-r", "./basic-python-examples/requirements.txt" ,"--user"]

  - name: 'python:3.10-slim'
    id: Create BigQuery datasets
    entrypoint: 'bash'
    args: ["./basic-python-examples/scripts/create-multiple-datasets.sh",]
    env:
      - "LOCATION=$LOCATION"
